response_column = "site_eui"
id_column = "id"  # probably not useful?
year_columns = "year_factor"  # probably use as cross validation?

below_temp_col_list = [
    "days_below_30f",
    "days_below_20f",
    "days_below_10f",
    "days_below_0f",
    "days_above_80f",
    "days_above_90f",
    "days_above_100f",
    "days_above_110f",
]

heat_cool_col_list = ["cooling_degree_days", "heating_degree_days"]

all_feature_columns = [
    "state_factor",  # not all state factor are in the test_df
    "building_class",
    "facility_type",
    "floor_area",
    "year_built",
    "energy_star_rating",
    "elevation",
    "january_min_temp",
    "january_avg_temp",
    "january_max_temp",
    "february_min_temp",
    "february_avg_temp",
    "february_max_temp",
    "march_min_temp",
    "march_avg_temp",
    "march_max_temp",
    "april_min_temp",
    "april_avg_temp",
    "april_max_temp",
    "may_min_temp",
    "may_avg_temp",
    "may_max_temp",
    "june_min_temp",
    "june_avg_temp",
    "june_max_temp",
    "july_min_temp",
    "july_avg_temp",
    "july_max_temp",
    "august_min_temp",
    "august_avg_temp",
    "august_max_temp",
    "september_min_temp",
    "september_avg_temp",
    "september_max_temp",
    "october_min_temp",
    "october_avg_temp",
    "october_max_temp",
    "november_min_temp",
    "november_avg_temp",
    "november_max_temp",
    "december_min_temp",
    "december_avg_temp",
    "december_max_temp",
    "cooling_degree_days",
    "heating_degree_days",
    "precipitation_inches",
    "snowfall_inches",
    "snowdepth_inches",
    "avg_temp",
    "days_below_30f",
    "days_below_20f",
    "days_below_10f",
    "days_below_0f",
    "days_above_80f",
    "days_above_90f",
    "days_above_100f",
    "days_above_110f",
    "direction_max_wind_speed",
    "direction_peak_wind_speed",
    "max_wind_speed",
    "days_with_fog",
]
