
response_column = "site_eui"
id_column = "id"  # probably not useful?
year_columns = "year_factor"  # probably use as cross validation?

below_temp_col_list = [
    "days_below_30f",
    "days_below_20f",
    "days_below_10f",
    "days_below_0f",
    "days_above_80f",
    "days_above_90f",
    "days_above_100f",
    "days_above_110f",
]

heat_cool_col_list = ["cooling_degree_days", "heating_degree_days"]

all_feature_columns = [
    "state_factor",  # not all state factor are in the test_df
    "building_class",
    "facility_type",
    "floor_area",
    "year_built",
    "energy_star_rating",
    "elevation",
    "january_min_temp",
    "january_avg_temp",
    "january_max_temp",
    "february_min_temp",
    "february_avg_temp",
    "february_max_temp",
    "march_min_temp",
    "march_avg_temp",
    "march_max_temp",
    "april_min_temp",
    "april_avg_temp",
    "april_max_temp",
    "may_min_temp",
    "may_avg_temp",
    "may_max_temp",
    "june_min_temp",
    "june_avg_temp",
    "june_max_temp",
    "july_min_temp",
    "july_avg_temp",
    "july_max_temp",
    "august_min_temp",
    "august_avg_temp",
    "august_max_temp",
    "september_min_temp",
    "september_avg_temp",
    "september_max_temp",
    "october_min_temp",
    "october_avg_temp",
    "october_max_temp",
    "november_min_temp",
    "november_avg_temp",
    "november_max_temp",
    "december_min_temp",
    "december_avg_temp",
    "december_max_temp",
    "cooling_degree_days",
    "heating_degree_days",
    "precipitation_inches",
    "snowfall_inches",
    "snowdepth_inches",
    "avg_temp",
    "days_below_30f",
    "days_below_20f",
    "days_below_10f",
    "days_below_0f",
    "days_above_80f",
    "days_above_90f",
    "days_above_100f",
    "days_above_110f",
    "direction_max_wind_speed",
    "direction_peak_wind_speed",
    "max_wind_speed",
    "days_with_fog",
]



temp_col_list = [
    "january_min_temp",
    "january_avg_temp",
    "january_max_temp",
    "february_min_temp",
    "february_avg_temp",
    "february_max_temp",
    "march_min_temp",
    "march_avg_temp",
    "march_max_temp",
    "april_min_temp",
    "april_avg_temp",
    "april_max_temp",
    "may_min_temp",
    "may_avg_temp",
    "may_max_temp",
    "june_min_temp",
    "june_avg_temp",
    "june_max_temp",
    "july_min_temp",
    "july_avg_temp",
    "july_max_temp",
    "august_min_temp",
    "august_avg_temp",
    "august_max_temp",
    "september_min_temp",
    "september_avg_temp",
    "september_max_temp",
    "october_min_temp",
    "october_avg_temp",
    "october_max_temp",
    "november_min_temp",
    "november_avg_temp",
    "november_max_temp",
    "december_min_temp",
    "december_avg_temp",
    "december_max_temp",
    "avg_temp",
]
wind_col_list = [
    "direction_max_wind_speed",
    "direction_peak_wind_speed",
    "max_wind_speed",
]
days_col_list = [
    # "cooling_degree_days",
    # "heating_degree_days",
    "days_below_30f",
    "days_below_20f",
    "days_below_10f",
    "days_below_0f",
    "days_above_80f",
    "days_above_90f",
    "days_above_100f",
    "days_above_110f",
    "days_with_fog",
]
inch_col_list = ["precipitation_inches", "snowfall_inches", "snowdepth_inches"]

## Feature cleaning/engineering configs
cols_to_drop = [
    "days_with_fog",
    "direction_max_wind_speed",
    "direction_peak_wind_speed",
    "max_wind_speed",
    "facility_type",
]

facility_type_dict = {
    "2to4_unit_building": "unit_building",
    "5plus_unit_building": "unit_building",
    "commercial_other": "commercial",
    "commercial_unknown": "commercial",
    "data_center": "data",
    "education_college_or_university": "education",
    "education_other_classroom": "education",
    "education_preschool_or_daycare": "education",
    "education_uncategorized": "education",
    "food_sales": "food",
    "food_service_other": "food",
    "food_service_restaurant_or_cafeteria": "food",
    "food_service_uncategorized": "food",
    "grocery_store_or_food_market": "grocery",
    "health_care_inpatient": "health",
    "health_care_outpatient_clinic": "health",
    "health_care_outpatient_uncategorized": "health",
    "health_care_uncategorized": "health",
    "industrial": "industrial",
    "laboratory": "laboratory",
    "lodging_dormitory_or_fraternity_sorority": "lodging",
    "lodging_hotel": "lodging",
    "lodging_other": "lodging",
    "lodging_uncategorized": "lodging",
    "mixed_use_commercial_and_residential": "commercial",
    "mixed_use_predominantly_commercial": "commercial",
    "mixed_use_predominantly_residential": "lodging",
    "multifamily_uncategorized": "lodging",
    "nursing_home": "health",
    "office_bank_or_other_financial": "office",
    "office_medical_non_diagnostic": "office",
    "office_mixed_use": "office",
    "office_uncategorized": "office",
    "parking_garage": "parking",
    "public_assembly_drama_theater": "public",
    "public_assembly_entertainment_culture": "public",
    "public_assembly_library": "public",
    "public_assembly_movie_theater": "public",
    "public_assembly_other": "public",
    "public_assembly_recreation": "public",
    "public_assembly_social_meeting": "public",
    "public_assembly_stadium": "public",
    "public_assembly_uncategorized": "public",
    "public_safety_courthouse": "public",
    "public_safety_fire_or_police_station": "public",
    "public_safety_penitentiary": "public",
    "public_safety_uncategorized": "public",
    "religious_worship": "religious",
    "retail_enclosed_mall": "retail",
    "retail_strip_shopping_mall": "retail",
    "retail_uncategorized": "retail",
    "retail_vehicle_dealership_showroom": "retail",
    "service_drycleaning_or_laundry": "laundry",
    "service_uncategorized": "service",
    "service_vehicle_service_repair_shop": "service",
    "warehouse_distribution_or_shipping_center": "warehouse",
    "warehouse_nonrefrigerated": "warehouse",
    "warehouse_refrigerated": "warehouse",
    "warehouse_selfstorage": "warehouse",
    "warehouse_uncategorized": "warehouse",
}

refridgerated_bool_dict = {
    "data_center": True,
    "food_service_restaurant_or_cafeteria": True,
    "food_sales": True,
    "grocery_store_or_food_market": True,
    "health_care_inpatient": True,
    "laboratory": True,
}